---
title: "R Notebook"
output: html_notebook
---

# R Environment

Using Renv
```{r, message=F, warning=F,results=F}
if (!requireNamespace("renv")) install.packages("renv")
renv::activate()
renv::restore()
#BiocManager::install("SingleR")
#BiocManager::install("celldex")
library(SingleR)
library(dplyr)
library(ggplot2)
library(scGate)
library(patchwork)
library(celldex)
source("utils.R")
library(ROCit)

library(scRNAseq)
#remotes::install_github("LTLA/scuttle")
library(scuttle)

#renv::snapshot()
#BiocManager::install("devtools")
#devtools::install_github("pcahan1/singleCellNet")

#library(singleCellNet)


## For testing data
#BiocManager::install("scRNAseq")
#library(scRNAseq)

library(BiocParallel)

```

# Load Jerby and Jost data 
```{r}
dataset.list <- readRDS("input/human.sets.dimred.rds")
dataset.list$Jerby <- AddMetaData(dataset.list$Jerby, dataset.list$Jerby$cell.types, col.name = "cell_type")
dataset.list$Yost <- AddMetaData(dataset.list$Yost, dataset.list$Yost$cluster, col.name = "cell_type")
Jerby.pred <- Yost.pred <- list()

```

```{r}
```

# SingleR
```{r}
hpca.se <- HumanPrimaryCellAtlasData()
```


```{r}
param <- MulticoreParam(workers = 32)

t0 = Sys.time()
Jerby.pred$SingleR.hpca <- SingleR(test = GetAssayData(dataset.list$Jerby), ref = hpca.se,labels = hpca.se$label.main, BPPARAM=param)
Yost.pred$SingleR.hpca <- SingleR(test = GetAssayData(dataset.list$Yost), ref = hpca.se,labels = hpca.se$label.main, BPPARAM=param)

t1 = Sys.time()
t1 -t0
```


```{r}
param <- MulticoreParam(workers = 60)

t0 = Sys.time()
Jerby.pred$SingleR.fine.hpca <- SingleR(test = GetAssayData(dataset.list$Jerby), ref = hpca.se,labels = hpca.se$label.fine, BPPARAM=param)
Yost.pred$SingleR.fine.hpca <- SingleR(test = GetAssayData(dataset.list$Yost), ref = hpca.se,labels = hpca.se$label.fine, BPPARAM=param)

t1 = Sys.time()
t1 -t0
Single
```

```{r}
hpca.se$label.fine%>%grep("T_cel",.,value = T)%>%unique()
```

## Now, we run SingleR but trained with Zilionis data
```{r}

sceZil <- scRNAseq::ZilionisLungData(which = "human")

# One should normally do cell-based quality control at this point, but for
# brevity's sake, we will just remove the unlabelled libraries here.
sceZil <- sceZil[,!is.na(sceZil$`Major cell type`)]

# SingleR() expects reference datasets to be normalized and log-transformed.
sceZil <- scuttle::logNormCounts(sceZil)
sceZil$`Most likely LM22 cell type`%>%table%>%sort(decreasing = T)%>%head()

param <- MulticoreParam(workers = 32)

t0 = Sys.time()
Jerby.pred$SingleR.Zil <- SingleR(test = GetAssayData(dataset.list$Jerby), ref = sceZil,labels = sceZil$`Most likely LM22 cell type`, BPPARAM=param)
Yost.pred$SingleR.Zil <- SingleR(test = GetAssayData(dataset.list$Yost), ref = sceZil,labels = sceZil$`Most likely LM22 cell type`, BPPARAM=param)

t1 = Sys.time()
t1 -t0

```


```{r}
Jerby.pred$SingleR.hpca$pruned.labels%>%table
Jerby.pred$SingleR.Zil$pruned.labels%>%table
```


```{r}
dataset.list$Jerby$cell_type%>%table
dataset.list$Yost$cell_type%>%table

```

## Tcell
```{r}
Jerby.pred$scGate.tcell <- scGate(dataset.list$Jerby,gating.model = scGate_DB$human$Tcell,sd.in = 4, sd.out = 7)
Jerby.pred$scGate.bcell <- scGate(dataset.list$Jerby,gating.model = scGate_DB$human$Bcell,sd.in = 4, sd.out = 7)
Jerby.pred$scGate.MoMacDen <- scGate(dataset.list$Jerby,gating.model = scGate_DB$human$Monocyte_Macrophage_Dendritic_pDendritic, sd.in = 4, sd.out = 7)
Jerby.pred$scGate.tcd8 <- scGate(dataset.list$Jerby,gating.model = scGate_DB$human$CD8.Tcell, sd.in = 4, sd.out = 7)
Jerby.pred$scGate.tcd4 <- scGate(dataset.list$Jerby,gating.model = scGate_DB$human$CD4.Tcell, sd.in = 4, sd.out = 7)


Yost.pred$scGate.tcell <- scGate(dataset.list$Yost,gating.model = scGate_DB$human$Tcell,sd.in = 4, sd.out = 7)
Yost.pred$scGate.bcell <- scGate(dataset.list$Yost,gating.model = scGate_DB$human$Bcell,sd.in = 4, sd.out = 7,max.impurity = 0.9)
Yost.pred$scGate.MoMacDen <- scGate(dataset.list$Yost,gating.model = scGate_DB$human$Monocyte_Macrophage_Dendritic_pDendritic, sd.in = 4, sd.out = 7)
Yost.pred$scGate.tcd8 <- scGate(dataset.list$Yost,gating.model = scGate_DB$human$CD8.Tcell, sd.in = 4, sd.out = 7)
Yost.pred$scGate.tcd4 <- scGate(dataset.list$Yost,gating.model = scGate_DB$human$CD4.Tcell, sd.in = 4, sd.out = 7)




```


```{r}
metric = "MCC"
#mccs <- data.frame(scGate = c(), SingleR = c(), SingleR.Zil = c(), target = c(),data = c())
mccs <- data.frame(mcc = c(),method = c(),target = c(), dataset = c())

a <- my.summary(actual = dataset.list$Jerby$cell_type%>%grepl("T.cell|T.CD4|T.CD8",.) + 0 ,pred = (Jerby.pred$scGate.tcell$is.pure== "Pure")+0)
b <- my.summary(actual = dataset.list$Jerby$cell_type%>%grepl("T.cell|T.CD4|T.CD8",.) + 0 ,pred = (Jerby.pred$SingleR.hpca$pruned.labels%>%grepl("T_cell",.)) + 0)
d <- my.summary(actual = dataset.list$Jerby$cell_type%>%grepl("T.cell|T.CD4|T.CD8",.) + 0 ,pred = (Jerby.pred$SingleR.Zil$pruned.labels%>%grepl("T cells",.)) + 0)
mccs <- rbind(mccs, data.frame(mcc = a$summary[[metric]], method = "scGate", target = "T.cell", dataset = "Jerby"))
mccs <- rbind(mccs, data.frame(mcc = b$summary[[metric]], method = "SingleR", target = "T.cell", dataset = "Jerby"))
mccs <- rbind(mccs, data.frame(mcc = d$summary[[metric]], method = "SingleR.Zil", target = "T.cell", dataset = "Jerby"))


a <- my.summary(actual = dataset.list$Jerby$cell_type%>%grepl("B.cell",.) + 0 ,pred = (Jerby.pred$scGate.bcell$is.pure== "Pure")+0)
b <- my.summary(actual = dataset.list$Jerby$cell_type%>%grepl("B.cell",.) + 0 ,pred = (Jerby.pred$SingleR.hpca$pruned.labels%>%grepl("B_cell",.)) + 0 )
d <- my.summary(actual = dataset.list$Jerby$cell_type%>%grepl("B.cell",.) + 0 ,pred = (Jerby.pred$SingleR.Zil$pruned.labels%>%grepl("B cells",.)) + 0)
mccs <- rbind(mccs, data.frame(mcc = a$summary[[metric]], method = "scGate", target = "B.cell", dataset = "Jerby"))
mccs <- rbind(mccs, data.frame(mcc = b$summary[[metric]], method = "SingleR", target = "B.cell", dataset = "Jerby"))
mccs <- rbind(mccs, data.frame(mcc = d$summary[[metric]], method = "SingleR.Zil", target = "B.cell", dataset = "Jerby"))


a <- my.summary(actual = dataset.list$Jerby$cell_type%>%grepl("Mon|Mac|DC",.) + 0 ,pred = (Jerby.pred$scGate.MoMacDen$is.pure== "Pure")+0)
b <- my.summary(actual = dataset.list$Jerby$cell_type%>%grepl("Mon|Mac|DC",.) + 0 ,pred = (Jerby.pred$SingleR.hpca$pruned.labels%>%grepl("Mon|Mac|DC",.)) + 0 )
d <- my.summary(actual = dataset.list$Jerby$cell_type%>%grepl("Mon|Mac|DC",.) + 0 ,pred = (Jerby.pred$SingleR.Zil$pruned.labels%>%grepl("Mon|Mac|Dend",.)) + 0)
mccs <- rbind(mccs, data.frame(mcc = a$summary[[metric]], method = "scGate", target = "MonMacDC", dataset = "Jerby"))
mccs <- rbind(mccs, data.frame(mcc = b$summary[[metric]], method = "SingleR", target = "MonMacDC", dataset = "Jerby"))
mccs <- rbind(mccs, data.frame(mcc = d$summary[[metric]], method = "SingleR.Zil", target = "MonMacDC", dataset = "Jerby"))


```

Yost
```{r}
## Yost 
a <- my.summary(actual = dataset.list$Yost$cell_type%>%grepl("T_cell|Tcell",.) + 0 ,pred = (Yost.pred$scGate.tcell$is.pure== "Pure")+0)
b <- my.summary(actual = dataset.list$Yost$cell_type%>%grepl("T_cell|Tcell",.) + 0 ,pred = (Yost.pred$SingleR.hpca$pruned.labels%>%grepl("T_cell",.)) + 0)
d <- my.summary(actual = dataset.list$Yost$cell_type%>%grepl("T.cell|T.CD4|T.CD8",.) + 0 ,pred = (Yost.pred$SingleR.Zil$pruned.labels%>%grepl("T cells",.)) + 0)
mccs <- rbind(mccs, data.frame(mcc = a$summary[[metric]], method = "scGate", target = "T.cell", dataset = "Yost"))
mccs <- rbind(mccs, data.frame(mcc = b$summary[[metric]], method = "SingleR", target = "T.cell", dataset = "Yost"))
mccs <- rbind(mccs, data.frame(mcc = d$summary[[metric]], method = "SingleR.Zil", target = "T.cell", dataset = "Yost"))




a <- my.summary(actual = dataset.list$Yost$cell_type%>%grepl("B_cell",.) + 0 ,pred = (Yost.pred$scGate.bcell$is.pure== "Pure")+0)
b <- my.summary(actual = dataset.list$Yost$cell_type%>%grepl("B_cell",.) + 0 ,pred = (Yost.pred$SingleR.hpca$pruned.labels%>%grepl("B_cell",.)) + 0 )
d <- my.summary(actual = dataset.list$Yost$cell_type%>%grepl("B_cell",.) + 0 ,pred = (Yost.pred$SingleR.Zil$pruned.labels%>%grepl("B cells",.)) + 0)
mccs <- rbind(mccs, data.frame(mcc = a$summary[[metric]], method = "scGate", target = "B.cell", dataset = "Yost"))
mccs <- rbind(mccs, data.frame(mcc = b$summary[[metric]], method = "SingleR", target = "B.cell", dataset = "Yost"))
mccs <- rbind(mccs, data.frame(mcc = d$summary[[metric]], method = "SingleR.Zil", target = "B.cell", dataset = "Yost"))


a <- my.summary(actual = dataset.list$Yost$cell_type%>%grepl("Mon|Mac|DC",.) + 0 ,pred = (Yost.pred$scGate.MoMacDen$is.pure== "Pure")+0)
b <- my.summary(actual = dataset.list$Yost$cell_type%>%grepl("Mon|Mac|DC",.) + 0 ,pred = (Yost.pred$SingleR.hpca$pruned.labels%>%grepl("Mon|Mac|DC",.)) + 0 )
d <- my.summary(actual = dataset.list$Yost$cell_type%>%grepl("Mon|Mac|DC",.) + 0 ,pred = (Yost.pred$SingleR.Zil$pruned.labels%>%grepl("Mon|Mac|Dend",.)) + 0)
mccs <- rbind(mccs, data.frame(mcc = a$summary[[metric]], method = "scGate", target = "MonMacDC", dataset = "Yost"))
mccs <- rbind(mccs, data.frame(mcc = b$summary[[metric]], method = "SingleR", target = "MonMacDC", dataset = "Yost"))
mccs <- rbind(mccs, data.frame(mcc = d$summary[[metric]], method = "SingleR.Zil", target = "MonMacDC", dataset = "Yost"))



```

## CD8 and CD4
```{r}

## T.CD8
a <- my.summary(actual = dataset.list$Jerby$cell_type%>%grepl("CD8",.) + 0 ,pred = (Jerby.pred$scGate.tcd8$is.pure== "Pure")+0)
b <- my.summary(actual = dataset.list$Jerby$cell_type%>%grepl("CD8",.) + 0 ,pred = (Jerby.pred$SingleR.Zil$pruned.labels%>%grepl("CD8",.)) + 0 )
d <- my.summary(actual = dataset.list$Jerby$cell_type%>%grepl("CD8",.) + 0 ,pred = (Jerby.pred$SingleR.fine.hpca$pruned.labels%>%grepl("CD8",.)) + 0)

mccs <- rbind(mccs, data.frame(mcc = a$summary[[metric]], method = "scGate", target = "TCD8", dataset = "Jerby"))
mccs <- rbind(mccs, data.frame(mcc = b$summary[[metric]], method = "SingleR.Zil", target = "TCD8", dataset = "Jerby"))
mccs <- rbind(mccs, data.frame(mcc = d$summary[[metric]], method = "SingleR.fine", target = "TCD8", dataset = "Jerby"))

## T.CD4
a <- my.summary(actual = dataset.list$Jerby$cell_type%>%grepl("CD4",.) + 0 ,pred = (Jerby.pred$scGate.tcd4$is.pure== "Pure")+0)
b <- my.summary(actual = dataset.list$Jerby$cell_type%>%grepl("CD4",.) + 0 ,pred = (Jerby.pred$SingleR.Zil$pruned.labels%>%grepl("CD4|Treg|helper",.)) + 0 )
d <- my.summary(actual = dataset.list$Jerby$cell_type%>%grepl("CD4",.) + 0 ,pred = (Jerby.pred$SingleR.fine.hpca$pruned.labels%>%grepl("CD4|Treg|helper",.)) + 0 )

mccs <- rbind(mccs, data.frame(mcc = a$summary[[metric]], method = "scGate", target = "TCD4", dataset = "Jerby"))
mccs <- rbind(mccs, data.frame(mcc = b$summary[[metric]], method = "SingleR.Zil", target = "TCD4", dataset = "Jerby"))
mccs <- rbind(mccs, data.frame(mcc = d$summary[[metric]], method = "SingleR.fine", target = "TCD4", dataset = "Jerby"))


#Yost
## T.CD8
a <- my.summary(actual = dataset.list$Yost$cell_type%>%grepl("CD8|prolif",.) + 0 ,pred = (Yost.pred$scGate.tcd8$is.pure== "Pure")+0)
b <- my.summary(actual = dataset.list$Yost$cell_type%>%grepl("CD8|prolif",.) + 0 ,pred = (Yost.pred$SingleR.Zil$pruned.labels%>%grepl("CD8",.)) + 0 )

d <- my.summary(actual = dataset.list$Yost$cell_type%>%grepl("CD8|prolif",.) + 0 ,pred = (Yost.pred$SingleR.fine.hpca$pruned.labels%>%grepl("CD8",.)) + 0 )

mccs <- rbind(mccs, data.frame(mcc = a$summary[[metric]], method = "scGate", target = "TCD8", dataset = "Yost"))
mccs <- rbind(mccs, data.frame(mcc = b$summary[[metric]], method = "SingleR.Zil", target = "TCD8", dataset = "Yost"))
mccs <- rbind(mccs, data.frame(mcc = d$summary[[metric]], method = "SingleR.fine", target = "TCD8", dataset = "Yost"))

## T.CD4
a <- my.summary(actual = dataset.list$Yost$cell_type%>%grepl("CD4|Tregs",.) + 0 ,pred = (Yost.pred$scGate.tcd4$is.pure== "Pure")+0)
b <- my.summary(actual = dataset.list$Yost$cell_type%>%grepl("CD4|Tregs",.) + 0 ,pred = (Yost.pred$SingleR.Zil$pruned.labels%>%grepl("CD4|Treg|helper",.)) + 0 )
d <- my.summary(actual = dataset.list$Yost$cell_type%>%grepl("CD4|Tregs",.) + 0 ,pred = (Yost.pred$SingleR.fine.hpca$pruned.labels%>%grepl("CD4|Treg|helper",.)) + 0 )

mccs <- rbind(mccs, data.frame(mcc = a$summary[[metric]], method = "scGate", target = "TCD4", dataset = "Yost"))
mccs <- rbind(mccs, data.frame(mcc = b$summary[[metric]], method = "SingleR.Zil", target = "TCD4", dataset = "Yost"))
mccs <- rbind(mccs, data.frame(mcc = d$summary[[metric]], method = "SingleR.fine", target = "TCD4", dataset = "Yost"))


```


```{r, fig.width= 10,fig.height=4.5}
jp <- ggplot(mccs%>%subset(dataset == "Jerby"),aes(fill=method, y=mcc, x=target)) + geom_bar(position="dodge", stat="identity") + ggtitle("Jerby") + ylab(metric)
yp <- ggplot(mccs%>%subset(dataset == "Yost"),aes(fill=method, y=mcc, x=target)) + geom_bar(position="dodge", stat="identity") + ggtitle("Yost") + ylab(metric)
jp + yp

```


```{r}
library(scRNAseq)
ld <- listDatasets()
human.ds <- ld%>%subset(Taxonomy == "9606")
mouse.ds <- ld%>%subset(Taxonomy == "10090")
zhao2020 <- ZhaoImmuneLiverData()

```





