---
title: "Intuitive Immune Isolation of cell types with scGate. Basic examples"
author: "M. Andreatta, A. Berenstein and S. Carmona"
date: "29/09/2021"
output:
  rmdformats::readthedown:
    self-contained: true
    highlight: haddock
    thumbnails: false
    css: styles.css
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file, encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'scGate.basic.usage.html'))})
---


```{r, message=F, warning=F,results=F}
renv::activate()
renv::restore()
library(ggplot2)
library(dplyr)
remotes::install_github("carmonalab/scGate", ref='dev')
library(scGate)
library(ggsignif)
library(ggpubr)
#renv::snapshot()
```


```{r setup, echo=FALSE, message=F, warning=F, results=F}
library(knitr)
library(rmdformats)
library(formatR)


## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               cache.lazy=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               dev='png')
opts_knit$set(width=75)
## figure output path 
figure.path <- "~/Dropbox/CSI/PAPERS/scGate/Figures"

```

## Load some testing datasets and models

Load datasets
```{r}
#testing.datasets <- scGate:::get_testing_data(version = 'hsa.latest')
testing.datasets <- readRDS("~/Dropbox/CSI/Datasets/human/human.sets.expanded.singler.rds")

```

Load default models from DB
```{r}
models.DB <- scGate::get_scGateDB(force_update = T)
models <- models.DB$human$generic  ## Human generic is a set of models trained for general purposes
print(models%>%names)

```

or alternatively, you can load models from your own personalized folder
```{r}
# models_path = '/home/user/path_to_your_own_model_folder'
# models <- scGate::load_models(models_path) 
```

### Have a look at some model
```{r, fig.height= 6,fig.width= 6, message=F,results=F}
model.name <- "Bcell"
model <- models[[model.name]]
plt.tree <- scGate::plot_tree(model)
plt.tree
```

```{r}
ground_truth_categories <- readRDS("~/Dropbox/CSI/Datasets/human/label_unification.rds")
```


## Run models and compute performance
```{r,collapse =T, results= F, echo = F}
# List available testing datasets:
t0 <- Sys.time()
results <- data.frame()
models <- models[names(models)!="Tcell.alphabeta"]
dset.to.run <- names(testing.datasets)
dset.to.run <- dset.to.run[!dset.to.run %in% c("bassez.c1")]
for(dset in dset.to.run){
  message(sprintf('runing %s',dset))
  obj <- testing.datasets[[dset]]
  assay <-  DefaultAssay(obj)
  for(model.name in names(models)){
    message(sprintf('runing %s',model.name))
    model <- models[[model.name]]
    obj <- scGate(obj, model = model, ncores = 1, keep.ranks = TRUE,
                                             output.col.name = paste0('is.pure.',model.name), assay = assay)
    
    res <- scGate::performance.metrics(actual = obj@meta.data[,model.name], pred = obj@meta.data[,paste0("is.pure.",model.name)] == "Pure")
    res <- data.frame(value = res, metric = names(res),model = model.name,dataset = dset,method = "scGate")
    results <- rbind(results,res)
    
    pred.singleR <- obj$SingleR.fine%>%grepl(ground_truth_categories$hpca_categories[[model.name]],.)+0
    singleR <- scGate::performance.metrics(actual = obj@meta.data[,model.name], pred = pred.singleR == 1)
    singleR <- data.frame(value = singleR, metric = names(singleR),model = model.name,dataset = dset,method = 'SingleR')
    results <- rbind(results,singleR)
    
  }

}
t1 <- Sys.time()
print(t1-t0)
```


## performance visualization

```{r,fig.width= 8, fig.height= 16}
res <- results%>%subset(metric %in% c("PREC","MCC") & dataset %in% c("PBMC_Satija","Jerby", "Yost","zilionis") )
plts <- ggplot(res, aes(x=model, y=value, fill=method)) + 
    geom_bar(position="dodge", stat="identity",width = 0.5) +
    facet_wrap(~ dataset + metric ,ncol = 2)  + theme_bw() +
   theme(
     strip.background = element_rect(
       color="white", fill="white", size=1.5, linetype="dashed"
       )
     ) + 
    theme(axis.text.x = element_text(angle = 60, vjust = 0.4, hjust=0.5)) 
#plts
```

```{r,fig.wirth = 8,fig.height=5}

data_summary <- function(x) {
   m <- mean(x)
   se <- function(x) sqrt(var(x)/length(x))
   ymin <- m-se(x)
   ymax <- m+se(x)
   return(c(y=m,ymin=ymin,ymax=ymax))
}

res <- results%>%subset(metric %in% c("PREC","MCC") & dataset %in% c("PBMC_Satija","Jerby", "Yost","zilionis") 
                        & model!= "Plasma_cell")


res.prec <- res%>%subset(metric == "PREC")
res.mcc <- res%>%subset(metric == "MCC")

plt.prec <- plts <- ggplot(res.prec, aes(x=model, y=value, color = method )) + geom_jitter(position=position_jitterdodge(jitter.width = 0.2), size = 0.4) +
  stat_summary(fun.data=data_summary,position=position_dodge(0.8), shape = 4, size = 0.25) + 
  ylab("Precision")   + theme_bw() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 60, vjust = 0.4, hjust=0.5)) 
  


plt.mcc  <- ggplot(res.mcc, aes(x=model, y=value, color=method )) + geom_jitter(position=position_jitterdodge(jitter.width = 0.2), size = 0.4) +
#  scale_color_manual(values=c("#E69F00", "#56B4E9")) + 
  stat_summary(fun.data=data_summary,  
               position=position_dodge(0.8), shape = 4, size = 0.25) + 
  ylab("MCC")  + theme_bw() +
  theme(legend.position = c(0.85, 0.15), legend.title = element_blank()) + 
  theme(axis.text.x = element_text(angle = 60, vjust = 0.4, hjust=0.5))

plts  = plt.prec + plt.mcc
plts
```


```{r,echo =FALSE, results=F}
saveRDS(results,file = file.path(figure.path,"benchmark_20102021_scGate.rds")) 
ggsave(file.path(figure.path,"benchmark_20102021_scGate.png"), plot=plts, width=9, height=5)
ggsave(file.path(figure.path,"benchmark_20102021_scGate.pdf"), plot=plts, width=9, height=5)

```

```{r,results=F, echo = F, eval=F}
faceted_plots <- ggplot(res, aes(x=model, y=value, fill = method )) + geom_boxplot() +
  facet_wrap(~ metric ,ncol = 2)  + theme_bw() + 
  theme(axis.text.x = element_text(angle = 60, vjust = 0.4, hjust=0.5)) +
     theme(
     strip.background = element_rect(
       color="white", fill="white", size=1.5, linetype="dashed"
       )
     ) 

```

