---
title: "Intuitive Immune Isolation of cell types with scGate. Basic examples"
author: "M. Andreatta, A. Berenstein and S. Carmona"
date: "29/09/2021"
output:
  rmdformats::readthedown:
    self-contained: true
    highlight: haddock
    thumbnails: false
    css: styles.css
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file, encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'scGate.basic.usage.html'))})
---


```{r, message=F, warning=F,results=F}
renv::restore()
library(ggplot2)
library(dplyr)
#remotes::install_github("carmonalab/scGate", ref='dev', force =T)
library(scGate)
#renv::snapshot()
```


```{r setup, echo=FALSE, message=F, warning=F, results=F}
library(knitr)
library(rmdformats)
library(formatR)


## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               cache.lazy=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               dev='png')
opts_knit$set(width=75)
## figure output path 
figure.path <- "~/Dropbox/CSI/PAPERS/scGate/Figures"

```

## Load some testing datasets and models

Load datasets
```{r}
testing.datasets <- readRDS(url("https://www.dropbox.com/s/8nugqcsjg2n26ba/testing.datasets.rds?dl=1"))
```

Load default models from DB
```{r}
models.DB <- scGate::get_scGateDB()
models <- models.DB$human$generic  ## Human generic is a set of models trained for general purposes
print(models%>%names)

```

or alternatively, you can load models from your own personalized folder
```{r}
# models_path = '/home/user/path_to_your_own_model_folder'
# models <- scGate::load_models(models_path) 
```

### Have a look at some model
```{r, fig.height= 6,fig.width= 6, message=F,results=F}
model.name <- "Bcell"
model <- models[[model.name]]
plt.tree <- scGate::plot_tree(model)
plt.tree
```

## Run models and compute performance
```{r,collapse =T, results= F, echo = F}
# List available testing datasets:
results <- data.frame()
for(dset in names(testing.datasets)[3]){
  message(sprintf('runing %s',dset))
  obj <- testing.datasets[[dset]]
  assay <-  DefaultAssay(obj)
  for(model.name in names(models)){
    message(sprintf('runing %s',model.name))
    model <- models[[model.name]]
    obj <- scGate(obj, model = model, ncores = 1, keep.ranks = TRUE,
                                             output.col.name = paste0('is.pure.',model.name), assay = assay)
    
    res <- scGate::performance.metrics(actual = obj@meta.data[,model.name], pred = obj@meta.data[,paste0("is.pure.",model.name)] == "Pure")
    res <- data.frame(value = res, metric = names(res),model = model.name,dataset = dset,method = "scGate")
    results <- rbind(results,res)

    singleR <- scGate::performance.metrics(actual = obj@meta.data[,model.name], pred = obj@meta.data[,paste0("SingleR_",model.name)] == 1)
    singleR <- data.frame(value = singleR, metric = names(singleR),model = model.name,dataset = dset,method = 'SingleR')
    results <- rbind(results,singleR)
    
  }

}
# Select one
```


## performance visualization

```{r,fig.width= 12, fig.height= 12}
plts <- ggplot(results, aes(x=model, y=value, fill=method)) + 
    geom_bar(position="dodge", stat="identity",width = 0.5) +
    facet_wrap(~ dataset + metric )  + theme_bw() +
   theme(
     strip.background = element_rect(
       color="white", fill="white", size=1.5, linetype="dashed"
       )
     ) + 
    theme(axis.text.x = element_text(angle = 60, vjust = 0.4, hjust=0.5)) 

plts
```


```{r,fig.width= 12, fig.height= 12,echo=F}
ggsave(file.path(figure.path,"benchmark_scGate.png"), plot=plts, width=14, height=14)
ggsave(file.path(figure.path,"benchmark_scGate.pdf"), plot=plts, width=14, height=14)

```