---
title: Test basic functionalities of scGate on human data
author: 
- Massimo Andreatta^[massimo.andreatta@unil.ch]
- Ariel Berenstein^[aberenstein@conicet.gov.ar]
- Santiago Carmona^[santiago.carmona@unil.ch]
date: "15/02/2021"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
#output: html_notebook
---


```{r message=F, warning=F}
renv::restore()
library(ggplot2)
library(dplyr)
remotes::install_github("carmonalab/scGate", ref='dev')
library(scGate)
library(SingleR)
library(dplyr)
library(BiocParallel)
library(patchwork)
library(parallel)
```



# Get some testing datasets
```{r}
dataset.list.all <- readRDS("~/Dropbox/CSI/Datasets/human/human.sets.expanded.singler.rds")
dataset.list.all <- dataset.list.all["bassez.c1"]
gc()
```

## Load Models from tables and impute them (if were necessary)
```{r}
models.DB <- scGate::get_scGateDB()
model <- models.DB$human$generic$CD8T  # model with 4 levels 
model$levels%>%unique()%>%length()
```

# Set parameters for time comparison
```{r}
timing <- list()
ncells <- c(250,500,1000,5000,10000,25000,50000)
whole.obj <- dataset.list.all$bassez.c1
```

### Load training data for SIngleR
```{r}
hpca.se <- HumanPrimaryCellAtlasData()  ## reference
param <- MulticoreParam(workers = 8)    # configure parallelization
```



# subset testing dataset (with different number of cells)  and run both models
```{r}
for(downsample in ncells){
  message(sprintf("runing methods with %s cells",downsample))
  
  # subset dataset
  subseted.obj <- subset(whole.obj, cells=sample(Cells(whole.obj),downsample))

  #scGate
  t0 <- Sys.time()
  test <- scGate(subseted.obj, model = model, ncores = 8)
  t1 <- Sys.time() 
  tt <- t1-t0
  deltaT <- as.numeric(tt, units = "mins")
  #reserve result
  timing[[paste0("Ncell_",downsample)]][["scGate"]] <- deltaT 
  
  
  
  #### SIngleR
  sr0 = Sys.time()
  test <- SingleR(test = GetAssayData(subseted.obj), ref = hpca.se, labels = hpca.se$label.fine, BPPARAM=param)
  sr1 = Sys.time()
  sr.tt <- sr1-sr0
  sr.deltaT <- as.numeric(sr.tt, units = "mins")
  #reserve result
  timing[[paste0("Ncell_",downsample)]][["SingleR"]] <- sr.deltaT
}
```





```{r}
res <- data.frame()

for(mtd in c("SingleR","scGate")){
  for(nc in ncells){
    a <- timing[[paste0("Ncell_",nc)]][[mtd]]
    if(is.null(a)){a <- NA}
    res <- rbind(res,data.frame("Ncell"= nc,method = mtd,time = a))
  }
}
```


```{r}
plt <- ggplot(res,aes(x=Ncell,y = time,
               group =method, colour = method)) + geom_line() + ylab("Time [min]")  + xlab("# cells") + geom_point() + theme_bw()
ggsave(filename = "~/Dropbox/CSI/PAPERS/scGate/Figures/time_benchmark_21102021.pdf",plot = plt)
ggsave(filename = "~/Dropbox/CSI/PAPERS/scGate/Figures/time_benchmark_21102021.png",plot = plt)
plt
```


